##Dealing with One Hot Encoding

In [13]:
import torch

In [16]:
def to_oneHot(y,numClasses):
  yOneHot = torch.zeros(y.size(0),numClasses)
  yOneHot.scatter_(1,y.view(-1,1).long(),1).float()
  return yOneHot




In [17]:
y = torch.tensor([0,1,2,2])

y_enc = to_oneHot(y,3)

print("One Hot Encoded form",y_enc)

One Hot Encoded form tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.]])


#Discovering SoftMax

In [18]:
z = torch.tensor([[-0.3,-0.5,-0.5],
                  [-0.4,-0.1,-0.5],
                  [-0.3,-0.94,-0.5],
                  [-0.99,-0.88,-0.5]])


In [19]:
z

tensor([[-0.3000, -0.5000, -0.5000],
        [-0.4000, -0.1000, -0.5000],
        [-0.3000, -0.9400, -0.5000],
        [-0.9900, -0.8800, -0.5000]])

In [24]:
def softmax(z):
  return (torch.exp(z.t()) / torch.sum(torch.exp(z),dim=1)).t()

In [25]:
smax = softmax(z)
print("Softmax",smax)

Softmax tensor([[0.3792, 0.3104, 0.3104],
        [0.3072, 0.4147, 0.2780],
        [0.4263, 0.2248, 0.3490],
        [0.2668, 0.2978, 0.4354]])


In [26]:
def to_classLabel(z):
  return torch.argmax(z,dim=1)

print("Predicted Class Labels" , to_classLabel(smax))
print("True Class Labels" , to_classLabel(y_enc))

Predicted Class Labels tensor([0, 1, 0, 2])
True Class Labels tensor([0, 1, 2, 2])


#Cross Entropy

In [27]:
def crossEntropy(softmax,yTar):
  return - torch.sum(torch.log(softmax)*(yTar) , dim=1)

xEnt = crossEntropy(smax,y_enc)
print("Cross Entropy", xEnt)

Cross Entropy tensor([0.9698, 0.8801, 1.0527, 0.8314])


#PyTorch Integrations

In [28]:
import torch.nn.functional as F


In [30]:
F.nll_loss(torch.log(smax),y,reduction='none')



tensor([0.9698, 0.8801, 1.0527, 0.8314])

In [31]:
F.cross_entropy(z,y,reduction='none')

tensor([0.9698, 0.8801, 1.0527, 0.8314])

## Both return the average of values which is necessary for stability

---



In [32]:
F.nll_loss(torch.log(smax),y)

tensor(0.9335)

In [33]:
F.cross_entropy(z,y)

tensor(0.9335)

In [34]:
torch.mean(xEnt)

tensor(0.9335)